name: lennujaam_dbt
version: "1.0.0"
profile: lennujaam_dbt

model-paths: ["models"]
snapshot-paths: ["snapshots"]
test-paths: ["tests"]
macro-paths: ["macros"]
seed-paths: ["seeds"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

data_tests:
  +store_failures: true

models:
  lennujaam_dbt:
    +persist_docs:
      relation: true
      columns: true
    silver:
      +materialized: view
      +schema: silver
    marts:
      +materialized: table
      +schema: marts


seeds:
  lennujaam_dbt:
    +schema: staging
    +quote_columns: false

    airports:
      +enabled: true
