version: 2


models:
  - name: dim_date
    description: "Date dimension table"
    columns:
      - name: date_key
        description: "Primary key (YYYYMMDD format)"
        tests:
          - unique
          - not_null

